/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import clases.scanner;
import clases.sintactico;
import clases.variables_guardar;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author arnol
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    sintactico sintax = new sintactico();
    scanner scan = new scanner();
    int xMouse, yMouse; //COORDENADAS DEL PUNTERO 
    public static String salida="";
    public Principal() {
        initComponents();
        this.getContentPane().setBackground(new Color(243,243,243)); //COLOR GRIS
        setLocationRelativeTo(null); //CENTRAR
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        button1 = new java.awt.Button();
        jButton2 = new javax.swing.JButton();
        abrirPanel = new javax.swing.JPanel();
        abrir = new javax.swing.JLabel();
        sintacticoPanel = new javax.swing.JPanel();
        sintactico = new javax.swing.JLabel();
        informacionPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        exitPanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        Título = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        txtDireccionArchivo = new javax.swing.JTextField();
        img1 = new javax.swing.JLabel();
        Panel_Abrir = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado_del_Archivo = new javax.swing.JTextArea();
        Panel_Sintactico = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnalizarSintax = new javax.swing.JTextArea();
        Panel_Consola = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        Panel_Semantico = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAnalizarSeman = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        button1.setLabel("button1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        abrirPanel.setBackground(new java.awt.Color(159, 230, 250));
        abrirPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        abrir.setBackground(new java.awt.Color(255, 255, 255));
        abrir.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        abrir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        abrir.setText("Abrir archivo");
        abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                abrirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                abrirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout abrirPanelLayout = new javax.swing.GroupLayout(abrirPanel);
        abrirPanel.setLayout(abrirPanelLayout);
        abrirPanelLayout.setHorizontalGroup(
            abrirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        abrirPanelLayout.setVerticalGroup(
            abrirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abrir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        sintacticoPanel.setBackground(new java.awt.Color(159, 230, 250));
        sintacticoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sintactico.setBackground(new java.awt.Color(255, 255, 255));
        sintactico.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        sintactico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sintactico.setText("Análisis del código");
        sintactico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sintacticoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sintacticoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sintacticoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sintacticoPanelLayout = new javax.swing.GroupLayout(sintacticoPanel);
        sintacticoPanel.setLayout(sintacticoPanelLayout);
        sintacticoPanelLayout.setHorizontalGroup(
            sintacticoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(sintacticoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sintacticoPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sintactico, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );
        sintacticoPanelLayout.setVerticalGroup(
            sintacticoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
            .addGroup(sintacticoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sintacticoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sintactico, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        informacionPanel.setBackground(new java.awt.Color(209, 235, 247));
        informacionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        informacionPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel4.setText("LENGUAJES Y COMPILADORES ");

        jLabel5.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel5.setText("UNMSM - 2022");

        jLabel3.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel3.setText("RECONOCEDOR - GRUPO 11");

        javax.swing.GroupLayout informacionPanelLayout = new javax.swing.GroupLayout(informacionPanel);
        informacionPanel.setLayout(informacionPanelLayout);
        informacionPanelLayout.setHorizontalGroup(
            informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        informacionPanelLayout.setVerticalGroup(
            informacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
        );

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(243, 243, 243));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        exitPanel.setBackground(new java.awt.Color(243, 243, 243));

        exit.setBackground(new java.awt.Color(255, 153, 0));
        exit.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitPanelLayout = new javax.swing.GroupLayout(exitPanel);
        exitPanel.setLayout(exitPanelLayout);
        exitPanelLayout.setHorizontalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        exitPanelLayout.setVerticalGroup(
            exitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitPanelLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Título.setBackground(new java.awt.Color(243, 243, 243));
        Título.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0)), null));

        Titulo.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        Titulo.setText("Reconocedor de lenguaje");
        Titulo.setToolTipText("");
        Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout TítuloLayout = new javax.swing.GroupLayout(Título);
        Título.setLayout(TítuloLayout);
        TítuloLayout.setHorizontalGroup(
            TítuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TítuloLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        TítuloLayout.setVerticalGroup(
            TítuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TítuloLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Título, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(exitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Título, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtDireccionArchivo.setEditable(false);

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ingeniero-de-sistemas(2).jpg"))); // NOI18N

        Panel_Abrir.setBackground(new java.awt.Color(243, 243, 243));
        Panel_Abrir.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 255, 255), new java.awt.Color(0, 0, 0)));

        txtResultado_del_Archivo.setEditable(false);
        txtResultado_del_Archivo.setColumns(20);
        txtResultado_del_Archivo.setRows(5);
        jScrollPane1.setViewportView(txtResultado_del_Archivo);

        javax.swing.GroupLayout Panel_AbrirLayout = new javax.swing.GroupLayout(Panel_Abrir);
        Panel_Abrir.setLayout(Panel_AbrirLayout);
        Panel_AbrirLayout.setHorizontalGroup(
            Panel_AbrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Panel_AbrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_AbrirLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Panel_AbrirLayout.setVerticalGroup(
            Panel_AbrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Panel_AbrirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_AbrirLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );

        Panel_Sintactico.setBackground(new java.awt.Color(243, 243, 243));
        Panel_Sintactico.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(204, 255, 255)));

        txtAnalizarSintax.setEditable(false);
        txtAnalizarSintax.setColumns(20);
        txtAnalizarSintax.setRows(5);
        jScrollPane2.setViewportView(txtAnalizarSintax);

        javax.swing.GroupLayout Panel_SintacticoLayout = new javax.swing.GroupLayout(Panel_Sintactico);
        Panel_Sintactico.setLayout(Panel_SintacticoLayout);
        Panel_SintacticoLayout.setHorizontalGroup(
            Panel_SintacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SintacticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        Panel_SintacticoLayout.setVerticalGroup(
            Panel_SintacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SintacticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtConsola.setEditable(false);
        txtConsola.setColumns(20);
        txtConsola.setLineWrap(true);
        txtConsola.setRows(5);
        jScrollPane5.setViewportView(txtConsola);

        javax.swing.GroupLayout Panel_ConsolaLayout = new javax.swing.GroupLayout(Panel_Consola);
        Panel_Consola.setLayout(Panel_ConsolaLayout);
        Panel_ConsolaLayout.setHorizontalGroup(
            Panel_ConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Panel_ConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_ConsolaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Panel_ConsolaLayout.setVerticalGroup(
            Panel_ConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
            .addGroup(Panel_ConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_ConsolaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        txtAnalizarSeman.setEditable(false);
        txtAnalizarSeman.setColumns(20);
        txtAnalizarSeman.setLineWrap(true);
        txtAnalizarSeman.setRows(5);
        jScrollPane4.setViewportView(txtAnalizarSeman);

        javax.swing.GroupLayout Panel_SemanticoLayout = new javax.swing.GroupLayout(Panel_Semantico);
        Panel_Semantico.setLayout(Panel_SemanticoLayout);
        Panel_SemanticoLayout.setHorizontalGroup(
            Panel_SemanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SemanticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_SemanticoLayout.setVerticalGroup(
            Panel_SemanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_SemanticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("Consola:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(abrirPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(informacionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Panel_Abrir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Panel_Semantico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Panel_Consola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDireccionArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sintacticoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Panel_Sintactico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(abrirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sintacticoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtDireccionArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_Abrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Sintactico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Panel_Consola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Panel_Semantico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informacionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //SALIR
    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked
    //EFECTO VISUAL EN EL BOTON DE SALIDA
    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exitPanel.setBackground(Color.red);
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered
    
    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exitPanel.setBackground(new Color(243,243,243));
        exit.setForeground(Color.black);
    }//GEN-LAST:event_exitMouseExited
    //EFECTO DE ARRASTRE
    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        int x,y;
        x = evt.getXOnScreen(); //COORDENADAS X RESPECTO A LA PANTALLA
        y = evt.getYOnScreen(); //COORDENADAS Y RESPECTO A LA PANTALLA
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        xMouse = evt.getX(); //COORDENADAS X RESPECTO A LA ESQUINA SUPERIOR IZQUIERDA DEL FRAME
        yMouse = evt.getY(); //COORDENADAS Y RESPECTO A LA ESQUINA SUPERIOR IZQUIERDA DEL FRAME
    }//GEN-LAST:event_jPanel4MousePressed
    //LEER EL ARCHIVO
    private void abrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirMouseClicked
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(this);
        File archivo = chooser.getSelectedFile();

        if(archivo!=null){
            this.txtDireccionArchivo.setText(archivo.getAbsolutePath());
        }
        
        String ST;
        try{
            ST=new String(Files.readAllBytes(archivo.toPath()));
            this.txtResultado_del_Archivo.setText(ST);
        }catch(IOException ex){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

        String help=archivo.getPath();

        try{
            Scanner scan=new Scanner(new File(help));
            while(scan.hasNextLine()){
                this.sintax.crearCadena(scan.nextLine());
            }
        }catch(FileNotFoundException ex){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abrirMouseClicked
    //EFECTOS VISUALES EN LOS BOTONES
    private void sintacticoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sintacticoMouseEntered
        sintacticoPanel.setBackground(new Color(131,201,233));
        sintactico.setForeground(Color.white);
    }//GEN-LAST:event_sintacticoMouseEntered

    private void sintacticoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sintacticoMouseExited
        sintacticoPanel.setBackground(new Color(159,230,250));
        sintactico.setForeground(Color.black);
    }//GEN-LAST:event_sintacticoMouseExited

    private void abrirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirMouseEntered
        abrirPanel.setBackground(new Color(131,201,233));
        abrir.setForeground(Color.white);
    }//GEN-LAST:event_abrirMouseEntered

    private void abrirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirMouseExited
        abrirPanel.setBackground(new Color(159,230,250));
        abrir.setForeground(Color.black);
    }//GEN-LAST:event_abrirMouseExited
    //ANALISIS SINTÁCTICO
    private void sintacticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sintacticoMouseClicked
        sintax.Analisis();
        String texto="";
        Boolean verificar=Boolean.TRUE;//SI EL BOOL DE MANTIENE EN TRUE NO HAY ERRORES
        for(int i=0;i<sintax.errores.size();i++){
            if(sintax.errores.get(i)==Boolean.FALSE){ //SE ANALIZA SI HAY ERRORES EN DETERMINADAS LINEAS
                texto=texto+"Error en linea "+String.valueOf(i+1)+"\t"+sintax.cad_cand.get(i)+"\n";
                verificar = Boolean.FALSE;
            }
        }
        if(verificar){ //NO HUBO ERRORES
            texto = "Sin errores";
        }
        this.txtAnalizarSintax.setText(texto); //SE MUESTRA EL TEXTO OBTENIDO
        //POR SI SE QUIERE ABRIR OTRO DOCUMENTO
        sintax.resetBool();
        sintax=new sintactico();
        
       analisis_semantico();
    }//GEN-LAST:event_sintacticoMouseClicked

    private void analisis_semantico(){
        int cont = 1;
        String expresion = (String) txtResultado_del_Archivo.getText();

        String aux = "";
        String aux1 ="";
        String resultado = "LINEA " + cont + "\n";

        txtAnalizarSeman.setText(resultado);

        do{
            aux=scan.scanner(expresion + '$');
            if(aux.equals("Salto de linea")){
                cont++;
                resultado += "LINEA " + cont + "\n";
                System.out.println("");
            }
            if (scan.token.getTipo().equals("I")) {
                if((aux.equals("int")||aux.equals("float"))){
                    resultado += "<Tipo Dato>"+"\t"+aux+"\n";
                }else if(aux.equals("escribe")||aux.equals("lee")){
                    resultado += "<Instruccion>"+"\t"+aux+"\n";
                }else{
                    resultado += "<Idetificador>"+"\t"+aux+"\n";
                }
            }
            if(scan.token.getTipo().equals("O")||scan.token.getTipo().equals("OA")){
                if(scan.token.getTipo().equals("O")){
                    resultado += "<Operador>"+"\t"+aux+"\n";   
                }else{
                    resultado += "<Operador A>"+"\t"+aux+"\n";   
                }
            }
            if(scan.token.getTipo().equals("N")||scan.token.getTipo().equals("ND")){
                resultado += "<Numero>"+"\t"+aux+"\n";
            }
            txtAnalizarSeman.setText(resultado);
        }while(!aux.equals("$"));
        scan=new scanner();
        //Muestra el texto en consola
        System.out.println("\n\n===============");
        System.out.println("TEXTO COMPLETO:");
        System.out.println(expresion);
        String salida_consola=expresion;
        
        scanner scan_aux = new scanner();
        int i=0;
        String id;
        do{
            try{
                aux1=scan.scanner(expresion + '$');
                scan_aux.setI(scan.getI());
                //obtener el id que sigue
                id=scan_aux.scanner(expresion+'$');
                if(scan.token.getNom().equals("<<")&&(!scan_aux.token.getTipo().equals("N")||!scan_aux.token.getTipo().equals("ND"))){
                    //obtenemos el indice
                    i=variables_guardar.var.indexOf(scan_aux.token.getNom());

                    salida_consola=salida_consola.replace("escribe<<"+variables_guardar.var.get(i),"escribe<<"+String.valueOf(variables_guardar.val.get(i)));
                    if(salida_consola.contains("escribe<<"+String.valueOf(variables_guardar.val.get(i)))){
                        salida+="escribe<<"+String.valueOf(variables_guardar.val.get(i))+"\n";
                    }
                }
            }catch(Exception e){
                salida+="Variable '"+scan_aux.token.getNom()+"' no declarada\n";
            }
            
        }while(!aux1.equals("$"));
        txtConsola.setText(salida);
        salida="";
        variables_guardar.clear();
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Limpiar txt de entrada de archivo
        this.txtResultado_del_Archivo.setText(null);
        //Limpiar txt de analisis sintactico
        this.txtAnalizarSintax.setText(null);
        //Limpiar txt de analisis semantico
        this.txtAnalizarSeman.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Abrir;
    private javax.swing.JPanel Panel_Consola;
    private javax.swing.JPanel Panel_Semantico;
    private javax.swing.JPanel Panel_Sintactico;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel Título;
    private javax.swing.JLabel abrir;
    private javax.swing.JPanel abrirPanel;
    private java.awt.Button button1;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JLabel img1;
    private javax.swing.JPanel informacionPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel sintactico;
    private javax.swing.JPanel sintacticoPanel;
    private javax.swing.JTextArea txtAnalizarSeman;
    private javax.swing.JTextArea txtAnalizarSintax;
    private javax.swing.JTextArea txtConsola;
    private javax.swing.JTextField txtDireccionArchivo;
    private javax.swing.JTextArea txtResultado_del_Archivo;
    // End of variables declaration//GEN-END:variables
}
